/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisruptionsRouteImport } from './routes/disruptions'
import { Route as EntitiesRouteImport } from './routes/entities'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as SystemRouteImport } from './routes/system'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisruptionsRoute = DisruptionsRouteImport.update({
  id: '/disruptions',
  path: '/disruptions',
  getParentRoute: () => rootRouteImport,
} as any)
const EntitiesRoute = EntitiesRouteImport.update({
  id: '/entities',
  path: '/entities',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/disruptions': typeof DisruptionsRoute
  '/entities': typeof EntitiesRoute
  '/network': typeof NetworkRoute
  '/predictions': typeof PredictionsRoute
  '/system': typeof SystemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/disruptions': typeof DisruptionsRoute
  '/entities': typeof EntitiesRoute
  '/network': typeof NetworkRoute
  '/predictions': typeof PredictionsRoute
  '/system': typeof SystemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/disruptions': typeof DisruptionsRoute
  '/entities': typeof EntitiesRoute
  '/network': typeof NetworkRoute
  '/predictions': typeof PredictionsRoute
  '/system': typeof SystemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/disruptions' | '/entities' | '/network' | '/predictions' | '/system'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/disruptions' | '/entities' | '/network' | '/predictions' | '/system'
  id:
    | '__root__'
    | '/'
    | '/disruptions'
    | '/entities'
    | '/network'
    | '/predictions'
    | '/system'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DisruptionsRoute: typeof DisruptionsRoute
  EntitiesRoute: typeof EntitiesRoute
  NetworkRoute: typeof NetworkRoute
  PredictionsRoute: typeof PredictionsRoute
  SystemRoute: typeof SystemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disruptions': {
      id: '/disruptions'
      path: '/disruptions'
      fullPath: '/disruptions'
      preLoaderRoute: typeof DisruptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entities': {
      id: '/entities'
      path: '/entities'
      fullPath: '/entities'
      preLoaderRoute: typeof EntitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DisruptionsRoute: DisruptionsRoute,
  EntitiesRoute: EntitiesRoute,
  NetworkRoute: NetworkRoute,
  PredictionsRoute: PredictionsRoute,
  SystemRoute: SystemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
